<?php

namespace Database\Seeders;

use App\Models\Control;
use Illuminate\Database\Seeder;

class AnnexAControlsSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->controls() as $control) {
            Control::updateOrCreate(
                ['control_ref' => $control['control_ref']],
                $control,
            );
        }
    }

    private function controls(): array
    {
        return [
            // ─── A.5 Organisational Controls (37) ────────────────────────────────
            ['control_ref' => 'A.5.1',  'theme' => 'Organisational', 'name' => 'Policies for information security',
             'description' => 'Information security policy and topic-specific policies shall be defined, approved by management, published, communicated to and acknowledged by relevant personnel and relevant interested parties, and reviewed at planned intervals and if significant changes occur.'],
            ['control_ref' => 'A.5.2',  'theme' => 'Organisational', 'name' => 'Information security roles and responsibilities',
             'description' => 'Information security roles and responsibilities shall be defined and allocated according to the organisation needs.'],
            ['control_ref' => 'A.5.3',  'theme' => 'Organisational', 'name' => 'Segregation of duties',
             'description' => 'Conflicting duties and conflicting areas of responsibility shall be segregated.'],
            ['control_ref' => 'A.5.4',  'theme' => 'Organisational', 'name' => 'Management responsibilities',
             'description' => 'Management shall require all personnel to apply information security in accordance with the established information security policy, topic-specific policies and procedures of the organisation.'],
            ['control_ref' => 'A.5.5',  'theme' => 'Organisational', 'name' => 'Contact with authorities',
             'description' => 'The organisation shall establish and maintain contact with relevant authorities.'],
            ['control_ref' => 'A.5.6',  'theme' => 'Organisational', 'name' => 'Contact with special interest groups',
             'description' => 'The organisation shall establish and maintain contact with special interest groups or other specialist security forums and professional associations.'],
            ['control_ref' => 'A.5.7',  'theme' => 'Organisational', 'name' => 'Threat intelligence',
             'description' => 'Information relating to information security threats shall be collected and analysed to produce threat intelligence.'],
            ['control_ref' => 'A.5.8',  'theme' => 'Organisational', 'name' => 'Information security in project management',
             'description' => 'Information security shall be integrated into project management.'],
            ['control_ref' => 'A.5.9',  'theme' => 'Organisational', 'name' => 'Inventory of information and other associated assets',
             'description' => 'An inventory of information and other associated assets, including owners, shall be developed and maintained.'],
            ['control_ref' => 'A.5.10', 'theme' => 'Organisational', 'name' => 'Acceptable use of information and other associated assets',
             'description' => 'Rules for the acceptable use and procedures for handling information and other associated assets shall be identified, documented and implemented.'],
            ['control_ref' => 'A.5.11', 'theme' => 'Organisational', 'name' => 'Return of assets',
             'description' => 'Personnel and other interested parties as appropriate shall return all the organisation\'s assets in their possession upon change or termination of their employment, contract or agreement.'],
            ['control_ref' => 'A.5.12', 'theme' => 'Organisational', 'name' => 'Classification of information',
             'description' => 'Information shall be classified according to the information security needs of the organisation based on confidentiality, integrity, availability and relevant interested party requirements.'],
            ['control_ref' => 'A.5.13', 'theme' => 'Organisational', 'name' => 'Labelling of information',
             'description' => 'An appropriate set of procedures for information labelling shall be developed and implemented in accordance with the information classification scheme adopted by the organisation.'],
            ['control_ref' => 'A.5.14', 'theme' => 'Organisational', 'name' => 'Information transfer',
             'description' => 'Information transfer rules, procedures, or agreements shall be in place for all types of transfer facilities within the organisation and between the organisation and other parties.'],
            ['control_ref' => 'A.5.15', 'theme' => 'Organisational', 'name' => 'Access control',
             'description' => 'Rules to control physical and logical access to information and other associated assets shall be established and implemented based on business and information security requirements.'],
            ['control_ref' => 'A.5.16', 'theme' => 'Organisational', 'name' => 'Identity management',
             'description' => 'The full life cycle of identities shall be managed.'],
            ['control_ref' => 'A.5.17', 'theme' => 'Organisational', 'name' => 'Authentication information',
             'description' => 'Allocation and management of authentication information shall be controlled by a management process, including advising personnel on appropriate handling of authentication information.'],
            ['control_ref' => 'A.5.18', 'theme' => 'Organisational', 'name' => 'Access rights',
             'description' => 'Access rights to information and other associated assets shall be provisioned, reviewed, modified and removed in accordance with the organisation\'s topic-specific policy on and rules for access control.'],
            ['control_ref' => 'A.5.19', 'theme' => 'Organisational', 'name' => 'Information security in supplier relationships',
             'description' => 'Processes and procedures shall be defined and implemented to manage the information security risks associated with the use of supplier\'s products or services.'],
            ['control_ref' => 'A.5.20', 'theme' => 'Organisational', 'name' => 'Addressing information security within supplier agreements',
             'description' => 'Relevant information security requirements shall be established and agreed with each supplier based on the type of supplier relationship.'],
            ['control_ref' => 'A.5.21', 'theme' => 'Organisational', 'name' => 'Managing information security in the ICT supply chain',
             'description' => 'Processes and procedures shall be defined and implemented to manage the information security risks associated with the ICT products and services supply chain.'],
            ['control_ref' => 'A.5.22', 'theme' => 'Organisational', 'name' => 'Monitoring, review and change management of supplier services',
             'description' => 'The organisation shall regularly monitor, review, evaluate and manage change in supplier information security practices and service delivery.'],
            ['control_ref' => 'A.5.23', 'theme' => 'Organisational', 'name' => 'Information security for use of cloud services',
             'description' => 'Processes for acquisition, use, management and exit from cloud services shall be established in accordance with the organisation\'s information security requirements.'],
            ['control_ref' => 'A.5.24', 'theme' => 'Organisational', 'name' => 'Information security incident management planning and preparation',
             'description' => 'The organisation shall plan and prepare for managing information security incidents by defining, establishing and communicating information security incident management processes, roles and responsibilities.'],
            ['control_ref' => 'A.5.25', 'theme' => 'Organisational', 'name' => 'Assessment and decision on information security events',
             'description' => 'The organisation shall assess information security events and decide if they are to be categorised as information security incidents.'],
            ['control_ref' => 'A.5.26', 'theme' => 'Organisational', 'name' => 'Response to information security incidents',
             'description' => 'Information security incidents shall be responded to in accordance with the documented procedures.'],
            ['control_ref' => 'A.5.27', 'theme' => 'Organisational', 'name' => 'Learning from information security incidents',
             'description' => 'Knowledge gained from information security incidents shall be used to strengthen and improve the information security controls.'],
            ['control_ref' => 'A.5.28', 'theme' => 'Organisational', 'name' => 'Collection of evidence',
             'description' => 'The organisation shall establish and implement procedures for the identification, collection, acquisition and preservation of evidence related to information security events.'],
            ['control_ref' => 'A.5.29', 'theme' => 'Organisational', 'name' => 'Information security during disruption',
             'description' => 'The organisation shall plan how to maintain information security at an appropriate level during disruption.'],
            ['control_ref' => 'A.5.30', 'theme' => 'Organisational', 'name' => 'ICT readiness for business continuity',
             'description' => 'ICT readiness shall be planned, implemented, maintained and tested based on business continuity objectives and ICT continuity requirements.'],
            ['control_ref' => 'A.5.31', 'theme' => 'Organisational', 'name' => 'Legal, statutory, regulatory and contractual requirements',
             'description' => 'Legal, statutory, regulatory and contractual requirements relevant to information security and the organisation\'s approach to meet these requirements shall be identified, documented and kept up to date.'],
            ['control_ref' => 'A.5.32', 'theme' => 'Organisational', 'name' => 'Intellectual property rights',
             'description' => 'The organisation shall implement appropriate procedures to protect intellectual property rights.'],
            ['control_ref' => 'A.5.33', 'theme' => 'Organisational', 'name' => 'Protection of records',
             'description' => 'Records shall be protected from loss, destruction, falsification, unauthorised access and unauthorised release.'],
            ['control_ref' => 'A.5.34', 'theme' => 'Organisational', 'name' => 'Privacy and protection of personally identifiable information',
             'description' => 'The organisation shall identify and meet the requirements regarding the preservation of privacy and protection of PII according to applicable laws and regulations and contractual requirements.'],
            ['control_ref' => 'A.5.35', 'theme' => 'Organisational', 'name' => 'Independent review of information security',
             'description' => 'The organisation\'s approach to managing information security and its implementation including people, processes and technologies shall be reviewed independently at planned intervals, or when significant changes occur.'],
            ['control_ref' => 'A.5.36', 'theme' => 'Organisational', 'name' => 'Compliance with policies, rules and standards for information security',
             'description' => 'Compliance with the organisation\'s information security policy, topic-specific policies, rules and standards shall be regularly reviewed.'],
            ['control_ref' => 'A.5.37', 'theme' => 'Organisational', 'name' => 'Documented operating procedures',
             'description' => 'Operating procedures for information processing facilities shall be documented and made available to personnel who need them.'],

            // ─── A.6 People Controls (8) ─────────────────────────────────────────
            ['control_ref' => 'A.6.1', 'theme' => 'People', 'name' => 'Screening',
             'description' => 'Background verification checks on all candidates to become personnel shall be carried out prior to joining the organisation and on an ongoing basis taking into consideration applicable laws, regulations and ethics and be proportional to the business requirements, the classification of the information to be accessed and the perceived risks.'],
            ['control_ref' => 'A.6.2', 'theme' => 'People', 'name' => 'Terms and conditions of employment',
             'description' => 'The employment contractual agreements shall state the personnel\'s and the organisation\'s responsibilities for information security.'],
            ['control_ref' => 'A.6.3', 'theme' => 'People', 'name' => 'Information security awareness, education and training',
             'description' => 'Personnel of the organisation and relevant interested parties shall receive appropriate information security awareness, education and training and regular updates of the organisation\'s information security policy, topic-specific policies and procedures, as relevant for their job function.'],
            ['control_ref' => 'A.6.4', 'theme' => 'People', 'name' => 'Disciplinary process',
             'description' => 'A disciplinary process shall be formalised and communicated to take actions against personnel and other relevant interested parties who have committed an information security policy violation.'],
            ['control_ref' => 'A.6.5', 'theme' => 'People', 'name' => 'Responsibilities after termination or change of employment',
             'description' => 'Information security responsibilities and duties that remain valid after termination or change of employment shall be defined, enforced and communicated to relevant personnel and other interested parties.'],
            ['control_ref' => 'A.6.6', 'theme' => 'People', 'name' => 'Confidentiality or non-disclosure agreements',
             'description' => 'Confidentiality or non-disclosure agreements reflecting the organisation\'s needs for the protection of information shall be identified, documented, regularly reviewed and signed by personnel and other relevant interested parties.'],
            ['control_ref' => 'A.6.7', 'theme' => 'People', 'name' => 'Remote working',
             'description' => 'Security measures shall be implemented when personnel are working remotely to protect information accessed, processed or stored outside the organisation\'s premises.'],
            ['control_ref' => 'A.6.8', 'theme' => 'People', 'name' => 'Information security event reporting',
             'description' => 'The organisation shall provide a mechanism for personnel to report observed or suspected information security events through appropriate channels in a timely manner.'],

            // ─── A.7 Physical Controls (14) ──────────────────────────────────────
            ['control_ref' => 'A.7.1',  'theme' => 'Physical', 'name' => 'Physical security perimeters',
             'description' => 'Security perimeters shall be defined and used to protect areas that contain information and other associated assets.'],
            ['control_ref' => 'A.7.2',  'theme' => 'Physical', 'name' => 'Physical entry',
             'description' => 'Secure areas shall be protected by appropriate entry controls and access points.'],
            ['control_ref' => 'A.7.3',  'theme' => 'Physical', 'name' => 'Securing offices, rooms and facilities',
             'description' => 'Physical security for offices, rooms and facilities shall be designed and implemented.'],
            ['control_ref' => 'A.7.4',  'theme' => 'Physical', 'name' => 'Physical security monitoring',
             'description' => 'Premises shall be continuously monitored for unauthorised physical access.'],
            ['control_ref' => 'A.7.5',  'theme' => 'Physical', 'name' => 'Protecting against physical and environmental threats',
             'description' => 'Protection against physical and environmental threats, such as natural disasters and other intentional or unintentional physical threats to infrastructure shall be designed and implemented.'],
            ['control_ref' => 'A.7.6',  'theme' => 'Physical', 'name' => 'Working in secure areas',
             'description' => 'Security measures for working in secure areas shall be designed and implemented.'],
            ['control_ref' => 'A.7.7',  'theme' => 'Physical', 'name' => 'Clear desk and clear screen',
             'description' => 'Clear desk rules for papers and removable storage media and clear screen rules for information processing facilities shall be defined and appropriately enforced.'],
            ['control_ref' => 'A.7.8',  'theme' => 'Physical', 'name' => 'Equipment siting and protection',
             'description' => 'Equipment shall be sited securely and protected.'],
            ['control_ref' => 'A.7.9',  'theme' => 'Physical', 'name' => 'Security of assets off-premises',
             'description' => 'Off-site assets shall be protected.'],
            ['control_ref' => 'A.7.10', 'theme' => 'Physical', 'name' => 'Storage media',
             'description' => 'Storage media shall be managed through their life cycle of acquisition, use, transportation and disposal in accordance with the organisation\'s classification scheme and handling requirements.'],
            ['control_ref' => 'A.7.11', 'theme' => 'Physical', 'name' => 'Supporting utilities',
             'description' => 'Information processing facilities shall be protected from power failures and other disruptions caused by failures in supporting utilities.'],
            ['control_ref' => 'A.7.12', 'theme' => 'Physical', 'name' => 'Cabling security',
             'description' => 'Cables carrying power, data or supporting information services shall be protected from interception, interference or damage.'],
            ['control_ref' => 'A.7.13', 'theme' => 'Physical', 'name' => 'Equipment maintenance',
             'description' => 'Equipment shall be maintained correctly to ensure availability, integrity and confidentiality of information.'],
            ['control_ref' => 'A.7.14', 'theme' => 'Physical', 'name' => 'Secure disposal or re-use of equipment',
             'description' => 'Items of equipment containing storage media shall be verified to ensure that any sensitive data and licensed software has been removed or securely overwritten prior to disposal or re-use.'],

            // ─── A.8 Technological Controls (34) ─────────────────────────────────
            ['control_ref' => 'A.8.1',  'theme' => 'Technological', 'name' => 'User endpoint devices',
             'description' => 'Information stored on, processed by or accessible via user endpoint devices shall be protected.'],
            ['control_ref' => 'A.8.2',  'theme' => 'Technological', 'name' => 'Privileged access rights',
             'description' => 'The allocation and use of privileged access rights shall be restricted and managed.'],
            ['control_ref' => 'A.8.3',  'theme' => 'Technological', 'name' => 'Information access restriction',
             'description' => 'Access to information and other associated assets shall be restricted in accordance with the established topic-specific policy on access control.'],
            ['control_ref' => 'A.8.4',  'theme' => 'Technological', 'name' => 'Access to source code',
             'description' => 'Read and write access to source code, development tools and software libraries shall be managed appropriately.'],
            ['control_ref' => 'A.8.5',  'theme' => 'Technological', 'name' => 'Secure authentication',
             'description' => 'Secure authentication technologies and procedures shall be implemented based on information access restrictions and the topic-specific policy on access control.'],
            ['control_ref' => 'A.8.6',  'theme' => 'Technological', 'name' => 'Capacity management',
             'description' => 'The use of resources shall be monitored and adjusted in line with current and expected capacity requirements.'],
            ['control_ref' => 'A.8.7',  'theme' => 'Technological', 'name' => 'Protection against malware',
             'description' => 'Protection against malware shall be implemented and supported by appropriate user awareness.'],
            ['control_ref' => 'A.8.8',  'theme' => 'Technological', 'name' => 'Management of technical vulnerabilities',
             'description' => 'Information about technical vulnerabilities of information systems in use shall be obtained, the organisation\'s exposure to such vulnerabilities evaluated and appropriate measures taken.'],
            ['control_ref' => 'A.8.9',  'theme' => 'Technological', 'name' => 'Configuration management',
             'description' => 'Configurations, including security configurations, of hardware, software, services and networks shall be established, documented, implemented, monitored and reviewed.'],
            ['control_ref' => 'A.8.10', 'theme' => 'Technological', 'name' => 'Information deletion',
             'description' => 'Information stored in information systems, devices or in any other storage media shall be deleted when no longer required.'],
            ['control_ref' => 'A.8.11', 'theme' => 'Technological', 'name' => 'Data masking',
             'description' => 'Data masking shall be used in accordance with the organisation\'s topic-specific policy on access control and other related topic-specific policies, and business requirements, taking applicable legislation into consideration.'],
            ['control_ref' => 'A.8.12', 'theme' => 'Technological', 'name' => 'Data leakage prevention',
             'description' => 'Data leakage prevention measures shall be applied to systems, networks and any other devices that process, store or transmit sensitive information.'],
            ['control_ref' => 'A.8.13', 'theme' => 'Technological', 'name' => 'Information backup',
             'description' => 'Backup copies of information, software and systems shall be maintained and regularly tested in accordance with the agreed topic-specific policy on backup.'],
            ['control_ref' => 'A.8.14', 'theme' => 'Technological', 'name' => 'Redundancy of information processing facilities',
             'description' => 'Information processing facilities shall be implemented with redundancy sufficient to meet availability requirements.'],
            ['control_ref' => 'A.8.15', 'theme' => 'Technological', 'name' => 'Logging',
             'description' => 'Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed.'],
            ['control_ref' => 'A.8.16', 'theme' => 'Technological', 'name' => 'Monitoring activities',
             'description' => 'Networks, systems and applications shall be monitored for anomalous behaviour and appropriate actions taken to evaluate potential information security incidents.'],
            ['control_ref' => 'A.8.17', 'theme' => 'Technological', 'name' => 'Clock synchronisation',
             'description' => 'The clocks of information processing systems used by the organisation shall be synchronised to approved time sources.'],
            ['control_ref' => 'A.8.18', 'theme' => 'Technological', 'name' => 'Use of privileged utility programs',
             'description' => 'The use of utility programs that can be capable of overriding system and application controls shall be restricted and tightly controlled.'],
            ['control_ref' => 'A.8.19', 'theme' => 'Technological', 'name' => 'Installation of software on operational systems',
             'description' => 'Procedures and measures shall be implemented to securely manage software installation on operational systems.'],
            ['control_ref' => 'A.8.20', 'theme' => 'Technological', 'name' => 'Networks security',
             'description' => 'Networks and network devices shall be secured, managed and controlled to protect information in systems and applications.'],
            ['control_ref' => 'A.8.21', 'theme' => 'Technological', 'name' => 'Security of network services',
             'description' => 'Security mechanisms, service levels and service requirements of network services shall be identified, implemented and monitored.'],
            ['control_ref' => 'A.8.22', 'theme' => 'Technological', 'name' => 'Segregation of networks',
             'description' => 'Groups of information services, users and information systems shall be segregated in the organisation\'s networks.'],
            ['control_ref' => 'A.8.23', 'theme' => 'Technological', 'name' => 'Web filtering',
             'description' => 'Access to external websites shall be managed to reduce exposure to malicious content.'],
            ['control_ref' => 'A.8.24', 'theme' => 'Technological', 'name' => 'Use of cryptography',
             'description' => 'Rules for the effective use of cryptography, including cryptographic key management, shall be defined and implemented.'],
            ['control_ref' => 'A.8.25', 'theme' => 'Technological', 'name' => 'Secure development life cycle',
             'description' => 'Rules for the secure development of software and systems shall be established and applied.'],
            ['control_ref' => 'A.8.26', 'theme' => 'Technological', 'name' => 'Application security requirements',
             'description' => 'Information security requirements shall be identified, specified and approved when developing or acquiring applications.'],
            ['control_ref' => 'A.8.27', 'theme' => 'Technological', 'name' => 'Secure system architecture and engineering principles',
             'description' => 'Principles for engineering secure systems shall be established, documented, maintained and applied to any information system development and acquisition activities.'],
            ['control_ref' => 'A.8.28', 'theme' => 'Technological', 'name' => 'Secure coding',
             'description' => 'Secure coding principles shall be applied to software development.'],
            ['control_ref' => 'A.8.29', 'theme' => 'Technological', 'name' => 'Security testing in development and acceptance',
             'description' => 'Security testing processes shall be defined and implemented in the development life cycle.'],
            ['control_ref' => 'A.8.30', 'theme' => 'Technological', 'name' => 'Outsourced development',
             'description' => 'The organisation shall direct, monitor and review the activities related to outsourced system development.'],
            ['control_ref' => 'A.8.31', 'theme' => 'Technological', 'name' => 'Separation of development, test and production environments',
             'description' => 'Development, testing and production environments shall be separated and secured.'],
            ['control_ref' => 'A.8.32', 'theme' => 'Technological', 'name' => 'Change management',
             'description' => 'Changes to information processing facilities and information systems shall be subject to change management procedures.'],
            ['control_ref' => 'A.8.33', 'theme' => 'Technological', 'name' => 'Test information',
             'description' => 'Test information shall be appropriately selected, protected and managed.'],
            ['control_ref' => 'A.8.34', 'theme' => 'Technological', 'name' => 'Protection of information systems during audit testing',
             'description' => 'Audit tests and other assurance activities involving assessment of operational systems shall be planned and agreed between the tester and appropriate management.'],
        ];
    }
}
